spring:
  application:
    name: rabbitmq-springboot
  profiles:
    active: dev2
logging:
  level:
    root : WARN
---
spring:
  rabbitmq:
    host: localhost
    port: 5672 # this 5672 is correct, our rabbit mq console management port is 15672
    username: wong
    password: guest
    virtual-host: /wong
  config:
    activate:
      on-profile: dev

---
spring:
  rabbitmq:
    host: localhost
    port: 5672 # this 5672 is correct, our rabbit mq console management port is 15672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 1s
    template:
      retry: # by default the retry max attempts is 3 times only, amqp retry was using blocking to retry
        enabled: true
        multiplier: 1
    # 3 type to choose - none, simple, correlated
    # none - close confirm mechanism
    # simple - synchronous block to wait MQ callback
    # correlated - MQ asynchronous call back method to return info
    publisher-confirm-type: correlated
    publisher-returns: true
  config:
    activate:
      on-profile: dev2
---




